language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
# command to run tests
script:
  - pytest --cov=./Tests
after_success:
  - codecov 
  
